
package com.mastering.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockServiceEndpoint", targetNamespace = "http://book.stock.jaxws.mastering.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StockServiceEndpoint {


    /**
     * 
     * @param code
     * @return
     *     returns int
     */
    @WebMethod(action = "RetrieveQuantityFromCode")
    @WebResult(name = "bookQuantity", targetNamespace = "")
    @RequestWrapper(localName = "bookQuantityByCode", targetNamespace = "http://book.stock.jaxws.mastering.com/", className = "com.mastering.jaxws.client.BookQuantityByCode")
    @ResponseWrapper(localName = "bookQuantityByCodeResponse", targetNamespace = "http://book.stock.jaxws.mastering.com/", className = "com.mastering.jaxws.client.BookQuantityByCodeResponse")
    @Action(input = "RetrieveQuantityFromCode", output = "http://book.stock.jaxws.mastering.com/StockServiceEndpoint/bookQuantityByCodeResponse")
    public int bookQuantityByCode(
        @WebParam(name = "code", targetNamespace = "")
        String code);

}
