
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockServiceEndpoint", targetNamespace = "http://book.stock.jaxws.mastering.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StockServiceEndpoint {


    /**
     * 
     * @param code
     * @return
     *     returns int
     */
    @WebMethod(action = "RetrieveQuantityFromCode")
    @WebResult(name = "bookQuantity", targetNamespace = "")
    @RequestWrapper(localName = "bookQuantityByCode", targetNamespace = "http://book.stock.jaxws.mastering.com/", className = "client.BookQuantityByCode")
    @ResponseWrapper(localName = "bookQuantityByCodeResponse", targetNamespace = "http://book.stock.jaxws.mastering.com/", className = "client.BookQuantityByCodeResponse")
    @Action(input = "RetrieveQuantityFromCode", output = "http://book.stock.jaxws.mastering.com/StockServiceEndpoint/bookQuantityByCodeResponse")
    public int bookQuantityByCode(
        @WebParam(name = "code", targetNamespace = "")
        String code);

    /**
     * 
     * @param codes
     * @return
     *     returns java.util.List<client.Book>
     */
    @WebMethod
    @WebResult(name = "booksList", targetNamespace = "")
    @RequestWrapper(localName = "booksFromItsCode", targetNamespace = "http://book.stock.jaxws.mastering.com/", className = "client.BooksFromItsCode")
    @ResponseWrapper(localName = "booksFromItsCodeResponse", targetNamespace = "http://book.stock.jaxws.mastering.com/", className = "client.BooksFromItsCodeResponse")
    @Action(input = "http://book.stock.jaxws.mastering.com/StockServiceEndpoint/booksFromItsCodeRequest", output = "http://book.stock.jaxws.mastering.com/StockServiceEndpoint/booksFromItsCodeResponse")
    public List<Book> booksFromItsCode(
        @WebParam(name = "codes", targetNamespace = "")
        List<String> codes);

}
